// Generated using Clyde :p
const ADJECTIVES = [
  "Brave",
  "Epic",
  "Exalted",
  "Fearless",
  "Formidable",
  "Gallant",
  "Grand",
  "Heroic",
  "Illustrious",
  "Indomitable",
  "Invincible",
  "Legendary",
  "Majestic",
  "Mighty",
  "Mythical",
  "Noble",
  "Regal",
  "Renowned",
  "Sovereign",
  "Sublime",
  "Triumphant",
  "Valiant",
  "Virtuous",
] as const;

const NOUNS = [
  "Act",
  "Adventure",
  "Anthem",
  "Army",
  "Artifact",
  "Artist",
  "Battle",
  "Career",
  "Castle",
  "Challenge",
  "Champion",
  "Character",
  "City",
  "Companion",
  "Destiny",
  "Effort",
  "Explorer",
  "Fame",
  "Force",
  "Fortress",
  "Heart",
  "Heritage",
  "Hero",
  "Horse",
  "Journey",
  "Knight",
  "Land",
  "Leader",
  "Leadership",
  "Legacy",
  "Legend",
  "Lineage",
  "Lion",
  "Moment",
  "Mountain",
  "Myth",
  "Poem",
  "Poet",
  "Power",
  "Presence",
  "Princess",
  "Queen",
  "Quest",
  "Realm",
  "Resolve",
  "Rival",
  "Ruler",
  "Sacrifice",
  "Scientist",
  "Soul",
  "Spirit",
  "Strength",
  "Sunrise",
  "Sunset",
  "Sword",
  "Tale",
  "Treasure",
  "Victory",
  "Warrior",
  "Waterfall",
  "Wisdom",
] as const;

export default function generateName() {
  const adjective = ADJECTIVES.at(Math.floor(Math.random() * ADJECTIVES.length));
  const noun = NOUNS.at(Math.floor(Math.random() * NOUNS.length));
  return `${adjective} ${noun}`;
}
